// About.js
import React from "react";

const About = () => {
  return (
    <div className="text-white w-[80%] mx-auto">
      <p className="mt-10 text-center px-3 ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, voluptate quas asperiores officia similique recusandae sed iste! Nostrum facilis quis delectus saepe sit iste distinctio nihil, illum quibusdam reiciendis eveniet quas. Dignissimos sequi placeat doloribus debitis vitae nulla voluptatum non? Dolor dignissimos ducimus ipsum quidem explicabo porro, perferendis nulla veniam asperiores temporibus maxime dolores. Vero, ea vel perferendis ipsam facere aliquid laboriosam? Maxime eius omnis ipsa voluptate deleniti, natus perferendis, aliquid tenetur a dignissimos voluptatibus assumenda, optio nemo ad fugit sed unde excepturi voluptatem neque hic sequi cum! Dicta itaque animi asperiores, eveniet quisquam molestiae non corporis quaerat ratione similique nam voluptatibus eum vel reprehenderit blanditiis ipsam saepe explicabo. Optio velit ad odio fugiat non! Dicta voluptatibus assumenda quos iste! Minima cum dolorum quaerat eum totam ex dolore incidunt placeat amet eligendi porro, harum cupiditate accusantium eaque aliquam ipsam laborum animi veritatis, quia ullam consectetur quasi, at nemo repellat! Eligendi veniam expedita tempore natus autem nisi facilis corrupti provident, et praesentium mollitia quam quas rem harum alias ut nam, culpa impedit voluptate? Ea quaerat veritatis inventore. Maxime, molestiae. Maxime iste distinctio voluptatum, labore necessitatibus ducimus laudantium eum facere similique suscipit repellendus deserunt debitis unde vitae ullam magnam voluptate inventore. Labore odit fugit, quas, animi sapiente nemo eius laudantium, corrupti cum quis sunt. Et deleniti qui vero consequatur error natus, dolores animi, aliquam, recusandae cum fugit! Sed reiciendis minima aliquid optio aperiam at laboriosam a dolore consectetur! Deserunt praesentium laborum itaque aliquam delectus enim eaque debitis placeat voluptatum optio tempora eligendi laboriosam nulla, ea est odit ab numquam recusandae impedit ullam mollitia error necessitatibus obcaecati pariatur? Nulla exercitationem, excepturi tenetur molestiae culpa dicta nobis possimus aliquid quod aspernatur ullam laborum hic doloremque aperiam repellat eveniet nisi ducimus. Corrupti minima, expedita qui sapiente magnam, accusamus eos facere consequatur delectus sunt eveniet repellat?</p>
    </div>
  );
};

export default About;
