// Feature.js
import React from "react";

const Feature = () => {
  return (
    <div className="text-white w-[80%] mx-auto">
      <p className="text-center px-5 mt-10">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt explicabo exercitationem repellendus necessitatibus fugit eligendi error temporibus voluptatibus nesciunt enim! Nam esse adipisci blanditiis? Dignissimos quidem obcaecati corporis et doloremque error dolor eligendi aperiam praesentium illum. Delectus laborum, iure ut quam cupiditate cumque quia molestiae numquam perferendis blanditiis omnis consectetur quos ex voluptas officia harum dicta id earum tempore fugiat labore accusantium in. Rem impedit tempora iusto iste fuga necessitatibus, ratione saepe repudiandae neque veritatis consectetur quae? Deleniti pariatur laudantium architecto, consequuntur reiciendis vel magnam similique placeat! Perferendis minus temporibus quod illo, accusantium ea nesciunt ab deleniti quasi, odio iure maiores iusto qui accusamus, dolores ipsum sunt consectetur repellendus aliquam enim earum eaque quo? Nostrum sequi fuga veritatis magni, incidunt at accusantium accusamus ea. Quos cum provident ratione quasi quo impedit, adipisci ipsum dicta sit reprehenderit iusto beatae, corporis totam vitae libero. Dolorum quis consectetur dolore! Quis doloremque quia atque quisquam ducimus, nostrum natus dolores similique soluta suscipit, numquam nisi neque maxime, saepe sit at voluptatibus sapiente ipsum ipsam dicta aperiam id odio. Omnis sint quisquam error optio vitae, accusantium voluptate asperiores veniam unde quod amet sequi minima cupiditate sapiente animi dolores illo. Expedita, aut. Assumenda magnam ab id eum, at repellat fuga. Veniam atque quas autem consequatur eveniet magni velit. Esse quo eaque cum autem minus, totam dolorem reiciendis accusantium laudantium nulla soluta, neque provident repudiandae corporis rem ipsam? Id, hic maxime totam exercitationem sit illo voluptatem eaque, expedita, odit quisquam quam reprehenderit dolores fugit incidunt pariatur et quia. Aperiam quisquam labore cumque perspiciatis enim iste corrupti voluptatum provident soluta odit nam, sint itaque pariatur rerum molestiae quaerat atque sed similique ducimus voluptate aut architecto natus. Laborum amet, excepturi numquam fugiat, earum unde voluptates veritatis aspernatur ad animi cupiditate soluta aut itaque tempora odit quo. Unde nihil eaque inventore.</p>
    </div>
  );
};

export default Feature;
