// Home.js
import React from "react";

const Home = () => {
  return (
    <div className="text-white w-[80%] mx-auto">
     <p className="mt-10 px-5 text-center">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis necessitatibus quod quia repudiandae ducimus saepe neque error voluptatibus quo voluptates. Deleniti voluptatibus beatae quia laudantium facere illo. Esse, consequuntur non! Nulla debitis, fuga velit eveniet quos iure omnis corrupti maiores exercitationem sed fugiat provident quia magnam similique consequatur error a quod quisquam commodi quae? Suscipit dolor ad dicta laudantium dolores quae, tempora voluptatem deserunt vel consectetur placeat expedita accusamus culpa fugiat autem aliquid ullam voluptatum corporis dolorum? Culpa reiciendis molestias id maiores explicabo porro aliquam perspiciatis vitae odit delectus eveniet magnam, aperiam quas nulla deleniti eos quos beatae dolore eaque cumque quaerat sunt modi dolores! Quasi necessitatibus dolorem odio repudiandae quaerat. Eligendi beatae laboriosam corrupti eos, laudantium consequuntur minus nisi fuga ad. Voluptatum dolorem corrupti suscipit doloremque voluptas quis illo modi maiores vitae, eligendi natus, rem reprehenderit accusamus eum minima nobis. Dolores architecto ea delectus, nam, quas non molestiae quisquam fugit blanditiis dolore suscipit ad quia autem aspernatur id a, quibusdam expedita. Vero nulla illo odio quam libero laudantium a laborum ipsam ab earum eligendi animi, aspernatur, eaque, amet et necessitatibus ipsum sed enim eum nostrum dolore iusto quae commodi? In, excepturi. Possimus natus sapiente alias exercitationem itaque doloribus facilis sint, officiis dolores. Ut quisquam qui tempora quaerat animi recusandae at nisi consectetur. Eligendi eveniet id, minus quam repellendus dolorem placeat voluptatem mollitia inventore similique reprehenderit tempore in nemo molestiae rem necessitatibus facilis commodi. In magni soluta maxime reiciendis earum voluptate voluptatibus quam dolorum! Possimus impedit iure aliquam perferendis distinctio cumque nobis voluptate, sapiente mollitia quasi! Illum recusandae quas nostrum iure voluptatum deleniti in rem dolores doloribus. Dicta excepturi facilis error quo expedita aut optio! Mollitia veritatis ipsa exercitationem, incidunt non accusantium qui totam possimus obcaecati inventore, consectetur enim autem eligendi eius similique sit quo, impedit ratione facere nobis praesentium.</p>
    </div>
  );
};

export default Home;
